import { MDXRemote } from "next-mdx-remote/rsc";
import { notFound } from "next/navigation";
import remarkGfm from "remark-gfm";
import {
  KpiCard,
  KpiGrid,
  ChartBar,
  WarningCallout,
} from "@/components/report";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { getReportData } from "@/lib/report-api";

const components = {
  KpiCard,
  KpiGrid,
  ChartBar,
  WarningCallout,
  Card,
  CardContent,
  CardHeader,
  CardTitle,
};

const mdxOptions = {
  mdxOptions: {
    remarkPlugins: [remarkGfm],
  },
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const data = await getReportData(id);

  if (!data) {
    return { title: "Report Not Found" };
  }

  return {
    title: `${data.execution.pipelineName} - Report ${id}`,
  };
}

export default async function PrintPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const data = await getReportData(id);

  if (!data) {
    notFound();
  }

  const { execution, mdxContent } = data;

  return (
    <article className="report-document">
      <header className="report-header">
        <h1>{execution.pipelineName}</h1>
        <div className="report-meta">
          <p>
            <strong>ID:</strong> {id}
          </p>
          <p>
            <strong>Generated:</strong>{" "}
            {new Date(execution.createdAt).toLocaleString()}
          </p>
          <p>
            <strong>Status:</strong> {execution.status}
          </p>
        </div>
      </header>

      <section className="report-content">
        <MDXRemote
          source={mdxContent}
          components={components}
          options={mdxOptions}
        />
      </section>

      <footer className="report-footer">
        <p>Generated by DProc Framework · {new Date().toLocaleDateString()}</p>
      </footer>
    </article>
  );
}
